"""Generate and install the Personal OS OpenClaw runtime surface."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tomllib
from pathlib import Path


GENERATED_HEADER = "<!-- GENERATED FILE - DO NOT EDIT\nSource: {source}\nGenerated by: scripts/generate_openclaw_surface.py\nTo update: edit canonical source, then run the generator.\n-->\n\n"
TOP_LEVEL_SOURCES = {
    "AGENTS.md": "docs/operating_system/templates/openclaw/AGENTS.md",
    "SOUL.md": "docs/operating_system/templates/openclaw/SOUL.md",
}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def output_files(root: Path) -> dict[Path, bytes]:
    outputs = {
        root / "generated_runtime" / "openclaw" / name: (
            GENERATED_HEADER.format(source=source).encode() + (root / source).read_bytes()
        )
        for name, source in TOP_LEVEL_SOURCES.items()
    }
    config = tomllib.loads((root / "repo_config" / "personal_agent.toml").read_text(encoding="utf-8"))
    identity = "# Personal CoS Identity\n\n" + "\n".join(
        f"- {key}: {config[key]}" for key in ("id", "role", "principal", "runtime", "harness")
    ) + "\n"
    outputs[root / "generated_runtime" / "openclaw" / "IDENTITY.md"] = (
        GENERATED_HEADER.format(source="repo_config/personal_agent.toml").encode()
        + identity.encode()
    )
    for skill in sorted((root / ".agents" / "skills").iterdir()):
        if skill.is_dir():
            destination = root / "generated_runtime" / "openclaw" / "skills" / skill.name / "SKILL.md"
            outputs[destination] = (skill / "SKILL.md").read_bytes()
    return outputs


def sync_repo(root: Path, check: bool) -> list[str]:
    drift: list[str] = []
    for path, content in output_files(root).items():
        if path.exists() and path.read_bytes() == content:
            continue
        drift.append(path.relative_to(root).as_posix())
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    return drift


def load_manifest(root: Path) -> dict:
    manifest = json.loads((root / "repo_config" / "runtime_surface_manifest.json").read_text(encoding="utf-8"))
    protected = {path.strip("/") for path in manifest["protectedPaths"]}
    managed = list(manifest["managedFiles"]) + list(manifest["managedDirectories"])
    conflicts = [
        path for path in managed
        if any(path == item or path.startswith(f"{item}/") for item in protected)
    ]
    if conflicts:
        raise ValueError(f"Manifest manages protected paths: {', '.join(conflicts)}")
    return manifest


def install(root: Path, install_dir: Path) -> None:
    manifest = load_manifest(root)
    generated = root / manifest["generatedRoot"]
    install_dir.mkdir(parents=True, exist_ok=True)
    for name in manifest["managedFiles"]:
        shutil.copy2(generated / name, install_dir / name)
    for skill in (generated / "skills").iterdir():
        if skill.is_dir():
            destination = install_dir / "skills" / skill.name
            destination.mkdir(parents=True, exist_ok=True)
            shutil.copy2(skill / "SKILL.md", destination / "SKILL.md")
    # ponytail: install leaves orphaned managed skills; add marker cleanup when runtime lifecycle needs deletion.


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report generated drift without writing.")
    parser.add_argument("--install-dir", type=Path, help="Install generated files into an OpenClaw workspace.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repo_root()
    drift = sync_repo(root, check=args.check)
    if args.check and drift:
        print("Generated surface drift:")
        print("\n".join(f"- {path}" for path in drift))
        return 1
    if args.install_dir:
        install(root, args.install_dir.expanduser().resolve())
    print("OpenClaw surface is up to date." if args.check else "OpenClaw surface generated.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
