"""Generate and install Personal OS runtime surfaces."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tomllib
from pathlib import Path, PurePosixPath, PureWindowsPath


GENERATED_HEADER = "<!-- GENERATED FILE - DO NOT EDIT\nSource: {source}\nGenerated by: scripts/generate_runtime_surface.py\nTo update: edit canonical source, then run the generator.\n-->\n\n"
TOML_GENERATED_HEADER = "# GENERATED FILE - DO NOT EDIT\n# Source: {source}\n# Generated by: scripts/generate_runtime_surface.py\n# Runtime: {runtime}\n# To update: edit canonical source, then run the generator.\n\n"
ENV_NAME_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")
FRONTEND_ROLES = {"edge-relay", "personal-cos"}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def is_safe_manifest_path(path: object) -> bool:
    if not isinstance(path, str) or not path:
        return False
    normalized = path.replace("\\", "/")
    return not (
        normalized.startswith("/")
        or PureWindowsPath(path).drive
        or any(part in {"", ".", ".."} for part in PurePosixPath(normalized).parts)
    )


def load_manifest(root: Path) -> dict:
    manifest = json.loads((root / "repo_config" / "runtime_surface_manifest.json").read_text(encoding="utf-8"))
    required = {"version", "protectedPaths"}
    if not isinstance(manifest, dict) or not required.issubset(manifest):
        raise ValueError("Manifest missing required fields")
    protected = manifest["protectedPaths"]
    if not isinstance(protected, list) or not all(is_safe_manifest_path(path) for path in protected):
        raise ValueError("Manifest contains unsafe protectedPaths")
    return manifest


def load_frontend_registry(root: Path) -> dict[str, dict]:
    path = root / "repo_config" / "frontend_registry.toml"
    registry = tomllib.loads(path.read_text(encoding="utf-8"))
    if registry.get("version") != 1 or registry.get("transport") != "local-process":
        raise ValueError("Frontend registry must use version 1 local-process transport")
    for field in ("edge_protocol", "dispatch_protocol", "event_protocol", "owner_principal"):
        if not isinstance(registry.get(field), str) or not registry[field]:
            raise ValueError(f"Frontend registry missing {field}")
    entries = registry.get("frontends")
    if not isinstance(entries, list) or not entries:
        raise ValueError("Frontend registry must contain frontends")
    result: dict[str, dict] = {}
    for entry in entries:
        if not isinstance(entry, dict):
            raise ValueError("Frontend entries must be objects")
        frontend_id = entry.get("id")
        if not isinstance(frontend_id, str) or not frontend_id or frontend_id in result:
            raise ValueError(f"Frontend IDs must be unique: {frontend_id}")
        if entry.get("role") not in FRONTEND_ROLES:
            raise ValueError(f"Unsupported frontend role: {frontend_id}")
        for field in ("runtime", "token_env"):
            if not isinstance(entry.get(field), str) or not entry[field]:
                raise ValueError(f"Frontend missing {field}: {frontend_id}")
        if not ENV_NAME_PATTERN.fullmatch(entry["token_env"]):
            raise ValueError(f"Invalid token environment name: {frontend_id}")
        result[frontend_id] = entry
    return result


def load_adapters(root: Path) -> list[dict]:
    adapters: list[dict] = []
    protected = load_manifest(root)["protectedPaths"]
    for directory in sorted((root / "adapters").iterdir()):
        if not directory.is_dir():
            continue
        path = directory / "manifest.toml"
        if not path.is_file():
            raise ValueError(f"Adapter missing manifest.toml: {directory.name}")
        manifest = tomllib.loads(path.read_text(encoding="utf-8"))
        if manifest.get("id") != directory.name:
            raise ValueError(f"Adapter ID does not match directory: {directory.name}")
        for field in ("id", "generatedRoot", "managedFiles", "managedDirectories", "sources"):
            if field not in manifest:
                raise ValueError(f"Adapter missing field: {directory.name}.{field}")
        if not is_safe_manifest_path(manifest["generatedRoot"]):
            raise ValueError(f"Adapter contains unsafe generatedRoot: {directory.name}")
        for field in ("managedFiles", "managedDirectories"):
            values = manifest[field]
            if not isinstance(values, list) or not all(is_safe_manifest_path(value) for value in values):
                raise ValueError(f"Adapter contains unsafe {field}: {directory.name}")
        sources = manifest["sources"]
        if not isinstance(sources, dict) or not all(
            is_safe_manifest_path(name) and is_safe_manifest_path(source)
            for name, source in sources.items()
        ):
            raise ValueError(f"Adapter contains unsafe sources: {directory.name}")
        if not set(sources).issubset(set(manifest["managedFiles"])):
            raise ValueError(f"Adapter sources must be managed files: {directory.name}")
        managed = manifest["managedFiles"] + manifest["managedDirectories"]
        if any(
            path == protected_path or path.startswith(f"{protected_path}/")
            for path in managed
            for protected_path in protected
        ):
            raise ValueError(f"Adapter manages protected paths: {directory.name}")
        if len(manifest["managedFiles"]) != len(set(manifest["managedFiles"])):
            raise ValueError(f"Adapter managed files must be unique: {directory.name}")
        if len(manifest["managedDirectories"]) != len(set(manifest["managedDirectories"])):
            raise ValueError(f"Adapter managed directories must be unique: {directory.name}")
        adapters.append(manifest)
    if not adapters:
        raise ValueError("No runtime adapters found")
    if len({adapter["id"] for adapter in adapters}) != len(adapters):
        raise ValueError("Runtime adapter IDs must be unique")
    return adapters


def adapter_output_files(root: Path, adapter: dict) -> dict[Path, bytes]:
    generated = root / adapter["generatedRoot"]
    frontend = load_frontend_registry(root).get(adapter["id"])
    if frontend is None or frontend["runtime"] != adapter["id"]:
        raise ValueError(f"Frontend registry entry does not match adapter: {adapter['id']}")
    outputs = {
        generated / name: GENERATED_HEADER.format(source=source).encode() + (root / source).read_bytes()
        for name, source in adapter["sources"].items()
    }
    config = tomllib.loads((root / "repo_config" / "personal_agent.toml").read_text(encoding="utf-8"))
    if frontend["role"] == "edge-relay":
        identity = (
            "# Edge Relay Identity\n\n"
            f"- id: {frontend['id']}\n"
            "- role: edge-relay\n"
            f"- principal: {config['principal']}\n"
            f"- runtime: {adapter['id']}\n"
        )
    else:
        identity = "# Personal CoS Identity\n\n" + "\n".join(
            f"- {key}: {config[key]}" for key in ("id", "role", "principal")
        ) + f"\n- runtime: {adapter['id']}\n"
    outputs[generated / "IDENTITY.md"] = (
        GENERATED_HEADER.format(source="repo_config/personal_agent.toml").encode() + identity.encode()
    )
    registry = root / "repo_config" / "tool_registry.toml"
    if frontend["role"] == "edge-relay":
        registry_bytes = b"version = 1\ncapabilities = []\n"
        registry_source = "repo_config/frontend_registry.toml"
    else:
        registry_bytes = registry.read_bytes()
        registry_source = "repo_config/tool_registry.toml"
    outputs[generated / "TOOL_REGISTRY.toml"] = (
        TOML_GENERATED_HEADER.format(runtime=adapter["id"], source=registry_source).encode()
        + registry_bytes
    )
    if frontend["role"] != "edge-relay":
        for skill in sorted((root / ".agents" / "skills").iterdir()):
            if skill.is_dir():
                outputs[generated / "skills" / skill.name / "SKILL.md"] = (skill / "SKILL.md").read_bytes()
    return outputs


def output_files(root: Path, runtime: str | None = None) -> dict[Path, bytes]:
    load_manifest(root)
    adapters = load_adapters(root)
    if runtime is not None:
        adapters = [adapter for adapter in adapters if adapter["id"] == runtime]
        if not adapters:
            raise ValueError(f"Unknown runtime adapter: {runtime}")
    outputs: dict[Path, bytes] = {}
    for adapter in adapters:
        outputs.update(adapter_output_files(root, adapter))
    return outputs


def sync_repo(root: Path, check: bool, runtime: str | None = None) -> list[str]:
    expected = output_files(root, runtime)
    drift: list[str] = []
    adapters = load_adapters(root)
    if runtime is not None:
        adapters = [adapter for adapter in adapters if adapter["id"] == runtime]
    for path, content in expected.items():
        if path.exists() and path.read_bytes() == content:
            continue
        drift.append(path.relative_to(root).as_posix())
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    for adapter in adapters:
        generated_root = root / adapter["generatedRoot"]
        stale = sorted(
            path for path in generated_root.rglob("*") if path.is_file() and path not in expected
        )
        for path in stale:
            drift.append(path.relative_to(root).as_posix())
            if not check:
                path.unlink()
                parent = path.parent
                while parent != generated_root and not any(parent.iterdir()):
                    parent.rmdir()
                    parent = parent.parent
    return drift


def install(root: Path, install_dir: Path, runtime: str) -> None:
    manifest = next(adapter for adapter in load_adapters(root) if adapter["id"] == runtime)
    generated = root / manifest["generatedRoot"]
    install_dir.mkdir(parents=True, exist_ok=True)
    for name in manifest["managedFiles"]:
        destination = install_dir / name
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(generated / name, destination)
    for directory in manifest["managedDirectories"]:
        source_dir = generated / directory
        for source in source_dir.rglob("*"):
            if source.is_file():
                destination = install_dir / directory / source.relative_to(source_dir)
                destination.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, destination)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report generated drift without writing.")
    parser.add_argument("--runtime", help="Runtime adapter ID; defaults to all adapters.")
    parser.add_argument("--install-dir", type=Path, help="Install one generated surface into a runtime workspace.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repo_root()
    if args.install_dir and not args.runtime:
        print("--install-dir requires --runtime", file=sys.stderr)
        return 2
    drift = sync_repo(root, check=args.check, runtime=args.runtime)
    if args.install_dir:
        install(root, args.install_dir.expanduser().resolve(), args.runtime)
    if args.check and drift:
        print("Generated surface drift:")
        print("\n".join(f"- {path}" for path in drift))
        return 1
    print("Runtime surfaces are up to date." if args.check else "Runtime surfaces generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
